services:
  order-db:
    image: postgres:16
    container_name: order_service_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_orders
    ports:
      - "5433:5432" # Host 5433 -> container 5432 (avoids local postgres on 5432)
    volumes:
      - order_db_data:/var/lib/postgresql/data

  order-app:
    profiles: ["fullstack"]
    build: .
    container_name: order_service_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/db_orders
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - order-db

volumes:
  order_db_data:
