package com.lynx.orderservice.domain;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents the Order entity within the application domain.
 * Includes detailed information about a trade request, such as unique identifiers,
 * {@link InstrumentType}, {@link OrderType}, {@link Side}, pricing details,
 * current {@link Status}, and relevant timestamps.
 */
@Entity
@Table(name = "orders")
public class Order{

    @Id
    @Column(name = "order_id", nullable = false, updatable = false)
    private UUID order_id;

    @Column(name = "platform_id", nullable = false)
    private UUID platform_id;

    @Column(name = "platform_user_id", nullable = false)
    private UUID platform_user_id;

    @Enumerated(EnumType.STRING)
    @Column(name = "instrument_type", nullable = false)
    private InstrumentType instrument_type;

    @Column(name = "instrument_id", nullable = false)
    private String instrument_id;

    @Enumerated(EnumType.STRING)
    @Column(name = "order_type", nullable = false)
    private OrderType order_type;

    @Enumerated(EnumType.STRING)
    @Column(name = "side", nullable = false)
    private Side side;

    @Column(name = "quantity", nullable = false)
    private BigDecimal quantity;

    @Column(name = "limit_price")
    private BigDecimal limit_price;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private Status status;

    @Column(name = "filled_quantity", nullable = false)
    private BigDecimal filled_quantity;

    @Column(name = "average_fill_price")
    private BigDecimal average_fill_price;

    @Column(name = "exchange_fee")
    private BigDecimal exchange_fee;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime created_at;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updated_at;

    @Column(name = "expires_at")
    private LocalDateTime expires_at;

    /**
     * Constructor without arguments required by Hibernate.
     */
    protected Order() {}

    /**
     * Constructs a fully initialized Order object.
     * <p>
     * This constructor is typically used when the order is retrieved from
     * the database or when manually instantiating a complete record.
     * </p>
     *
     * @param order_id the unique identifier generated by the exchange
     * @param platform_id the broker platform that submitted this order
     * @param platform_user_id the user on that platform who placed the order
     * @param instrument_type the type of the instrument (STOCK or OPTION)
     * @param instrument_id the ticker (for stocks) or option_id (for options)
     * @param order_type the type of the order (MARKET or LIMIT)
     * @param side the side of the trade (BUY or SELL)
     * @param quantity the number of shares or contracts
     * @param limit_price the specified price limit (required for LIMIT orders)
     * @param status the current execution status of the order
     * @param filled_quantity the number of units that have been filled so far
     * @param average_fill_price the weighted average price of executed fills
     * @param exchange_fee the total exchange fee charged on this order
     * @param created_at the simulated market timestamp of order creation
     * @param updated_at the simulated market timestamp of the last status change
     * @param expires_at the simulated market time after which a LIMIT order is cancelled
     */
    public Order(UUID order_id, UUID platform_id, UUID platform_user_id, InstrumentType instrument_type,
                 String instrument_id, OrderType order_type, Side side, BigDecimal quantity,
                 BigDecimal limit_price, Status status, BigDecimal filled_quantity,
                 BigDecimal average_fill_price, BigDecimal exchange_fee, LocalDateTime created_at,
                 LocalDateTime updated_at, LocalDateTime expires_at) {
        this.order_id = order_id;
        this.platform_id = platform_id;
        this.platform_user_id = platform_user_id;
        this.instrument_type = instrument_type;
        this.instrument_id = instrument_id;
        this.order_type = order_type;
        this.side = side;
        this.quantity = quantity;
        this.limit_price = limit_price;
        this.status = status;
        this.filled_quantity = filled_quantity;
        this.average_fill_price = average_fill_price;
        this.exchange_fee = exchange_fee;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.expires_at = expires_at;
    }

    /**
     * Returns the unique identifier of the order (alias for getID).
     * @return the order's ID
     */
    public UUID getOrder_id() {
        return order_id;
    }

    /**
     * Sets or updates the unique identifier of the order (alias for setID).
     * @param order_id the new ID of the order
     */
    public void setOrder_id(UUID order_id) {
        this.order_id = order_id;
    }

    /**
     * Returns the platform ID that submitted this order.
     * @return the platform's ID
     */
    public UUID getPlatform_id() {
        return platform_id;
    }

    /**
     * Sets or updates the platform ID that submitted this order.
     * @param platform_id the new platform ID
     */
    public void setPlatform_id(UUID platform_id) {
        this.platform_id = platform_id;
    }

    /**
     * Returns the user ID on the platform who placed the order.
     * @return the user's ID
     */
    public UUID getPlatform_user_id() {
        return platform_user_id;
    }

    /**
     * Sets or updates the user ID on the platform who placed the order.
     * @param platform_user_id the new user ID
     */
    public void setPlatform_user_id(UUID platform_user_id) {
        this.platform_user_id = platform_user_id;
    }

    /**
     * Returns the {@link InstrumentType} of the order.
     * @return the instrument type (e.g., STOCK, OPTION)
     */
    public InstrumentType getInstrument_type() {
        return instrument_type;
    }

    /**
     * Sets or updates the {@link InstrumentType} of the order.
     * @param instrument_type the new instrument type
     */
    public void setInstrument_type(InstrumentType instrument_type) {
        this.instrument_type = instrument_type;
    }

    /**
     * Returns the identifier of the specific instrument (e.g., ticker symbol).
     * @return the instrument's ID
     */
    public String getInstrument_id() {
        return instrument_id;
    }

    /**
     * Sets or updates the identifier of the specific instrument.
     * @param instrument_id the new instrument ID
     */
    public void setInstrument_id(String instrument_id) {
        this.instrument_id = instrument_id;
    }

    /**
     * Returns the {@link OrderType} of the order.
     * @return the order type (e.g., MARKET, LIMIT)
     */
    public OrderType getOrder_type() {
        return order_type;
    }

    /**
     * Sets or updates the {@link OrderType} of the order.
     * @param order_type the new order type
     */
    public void setOrder_type(OrderType order_type) {
        this.order_type = order_type;
    }

    /**
     * Returns the {@link Side} of the order (BUY or SELL).
     * @return the order's side
     */
    public Side getSide() {
        return side;
    }

    /**
     * Sets or updates the {@link Side} of the order.
     * @param side the new side
     */
    public void setSide(Side side) {
        this.side = side;
    }

    /**
     * Returns the requested quantity of shares or contracts.
     * @return the requested quantity
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets or updates the requested quantity of shares or contracts.
     * @param quantity the new requested quantity
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * Returns the limit price set for the order.
     * @return the limit price, or null if MARKET order
     */
    public BigDecimal getLimit_price() {
        return limit_price;
    }

    /**
     * Sets or updates the limit price for the order.
     * @param limit_price the new limit price
     */
    public void setLimit_price(BigDecimal limit_price) {
        this.limit_price = limit_price;
    }

    /**
     * Returns the current {@link Status} of the order.
     * @return the order's status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets or updates the current {@link Status} of the order.
     * @param status the new status
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Returns the quantity of units that have been filled so far.
     * @return the filled quantity
     */
    public BigDecimal getFilled_quantity() {
        return filled_quantity;
    }

    /**
     * Sets or updates the quantity of units that have been filled so far.
     * @param filled_quantity the new filled quantity
     */
    public void setFilled_quantity(BigDecimal filled_quantity) {
        this.filled_quantity = filled_quantity;
    }

    /**
     * Returns the weighted average price of executed fills.
     * @return the average fill price
     */
    public BigDecimal getAverage_fill_price() {
        return average_fill_price;
    }

    /**
     * Sets or updates the weighted average price of executed fills.
     * @param average_fill_price the new average fill price
     */
    public void setAverage_fill_price(BigDecimal average_fill_price) {
        this.average_fill_price = average_fill_price;
    }

    /**
     * Returns the total exchange fee charged on this order.
     * @return the exchange fee
     */
    public BigDecimal getExchange_fee() {
        return exchange_fee;
    }

    /**
     * Sets or updates the total exchange fee charged on this order.
     * @param exchange_fee the new exchange fee
     */
    public void setExchange_fee(BigDecimal exchange_fee) {
        this.exchange_fee = exchange_fee;
    }

    /**
     * Returns the simulated market timestamp when the order was created.
     * @return the creation timestamp
     */
    public LocalDateTime getCreated_at() {
        return created_at;
    }

    /**
     * Sets or updates the simulated market timestamp of order creation.
     * @param created_at the new creation timestamp
     */
    public void setCreated_at(LocalDateTime created_at) {
        this.created_at = created_at;
    }

    /**
     * Returns the simulated market timestamp of the last status change.
     * @return the last updated timestamp
     */
    public LocalDateTime getUpdated_at() {
        return updated_at;
    }

    /**
     * Sets or updates the simulated market timestamp of the last status change.
     * @param updated_at the new updated timestamp
     */
    public void setUpdated_at(LocalDateTime updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * Returns the simulated market time after which a LIMIT order expires.
     * @return the expiration timestamp
     */
    public LocalDateTime getExpires_at() {
        return expires_at;
    }

    /**
     * Sets or updates the simulated market time after which the order expires.
     * @param expires_at the new expiration timestamp
     */
    public void setExpires_at(LocalDateTime expires_at) {
        this.expires_at = expires_at;
    }
}