package com.lynx.orderservice.domain;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents the Order entity within the application domain.
 * Includes detailed information about a trade request, such as unique identifiers,
 * {@link InstrumentType}, {@link OrderType}, {@link Side}, pricing details,
 * current {@link Status}, and relevant timestamps.
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
public class Order {

    /** The unique identifier generated by the exchange. */
    @Id
    @Column(name = "order_id", nullable = false, updatable = false)
    private UUID orderId;

    /** The broker platform that submitted this order. */
    @Column(name = "platform_id", nullable = false)
    private UUID platformId;

    /** The user on that platform who placed the order. */
    @Column(name = "platform_user_id", nullable = false)
    private UUID platformUserId;

    /** The type of the instrument (STOCK or OPTION). */
    @Enumerated(EnumType.STRING)
    @Column(name = "instrument_type", nullable = false)
    private InstrumentType instrumentType;

    /** The ticker (for stocks) or option_id (for options). */
    @Column(name = "instrument_id", nullable = false)
    private String instrumentId;

    /** The type of the order (MARKET or LIMIT). */
    @Enumerated(EnumType.STRING)
    @Column(name = "order_type", nullable = false)
    private OrderType orderType;

    /** The side of the trade (BUY or SELL). */
    @Enumerated(EnumType.STRING)
    @Column(name = "side", nullable = false)
    private Side side;

    /** The number of shares or contracts. */
    @Column(name = "quantity", nullable = false)
    private BigDecimal quantity;

    /** The specified price limit (required for LIMIT orders). */
    @Column(name = "limit_price")
    private BigDecimal limitPrice;

    /** The current execution status of the order. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private Status status;

    /** The number of units that have been filled so far. */
    @Column(name = "filled_quantity", nullable = false)
    private BigDecimal filledQuantity;

    /** The weighted average price of executed fills. */
    @Column(name = "average_fill_price")
    private BigDecimal averageFillPrice;

    /** The total exchange fee charged on this order. */
    @Column(name = "exchange_fee")
    private BigDecimal exchangeFee;

    /** The simulated market timestamp of order creation. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** The simulated market timestamp of the last status change. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** The simulated market time after which a LIMIT order is cancelled. */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;
}